### ISSUE TITLE
Update tc-admin to be able to use proxy

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/fuzzing-tc#23]
TFW you realise tc-admin has no proxy support :fearful: 

I made [a patch](https://github.com/taskcluster/tc-admin/pull/63) to add proxy support, after a release is made, i'll simply bump the version in requirements and `tc-admin apply` will work out of the box.

**Comment by jschwartzentruber** [comment]
If this still blocks us when we're ready to deploy, we can either request a release of tc-admin or tell pip to use git (at least https://github.com/taskcluster/tc-admin/commit/e5d500ead7e4b8585ba8b185aa866f213f492bdb) rather than pypi.

**Comment by La0** [comment]
I asked Dustin to make a release of tc-admin this morning, and he delivered !
