### ISSUE TITLE
Delete existing tasks in a worker pool

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/fuzzing-tc#35]
We can list current tasks in a worker pool using `listWorkers` ([example](https://community-tc.services.mozilla.com/api/queue/v1/provisioners/proj-relman/worker-types/ci/workers) & [doc](https://docs.taskcluster.net/docs/reference/platform/queue/api#listWorkers))
For each task present in the list, we need to retrieve its status, if it's unscheduled, pending or running, we can call `cancelTask` ([doc](https://docs.taskcluster.net/docs/reference/platform/queue/api#cancelTask))

The decision task could do that on each new run, before creating new tasks. It seems easier to implement it outside of tc-admin, as we do not control directly the `apply` mechanism

**Comment by jschwartzentruber** [comment]
This implies that we have scopes to cancel tasks. Currently when I try to cancel a running task (via the web UI), I get a missing scope error:

```
{
  "AnyOf": [
    "queue:cancel-task:-/{taskGroupId}/{taskId}",
    {
      "AllOf": [
        "queue:cancel-task",
        "assume:scheduler-id:-/{taskGroupId}"
      ]
    }
  ]
}
```

**Comment by jschwartzentruber** [comment]
The scopes still aren't resolved. Disabled the API call in 1c055f7.
