### ISSUE TITLE
Investigate pre/post hooks in tc-admin

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/fuzzing-tc#47]
In order to run custom logic before, or especially after the main command has been done:
- to stop the tasks in a workerpool that will be updated/deleted
- to start a hook that has been created/updated

**Comment by La0** [comment]
See https://github.com/taskcluster/tc-admin/issues/67

**Comment by La0** [comment]
Made a PR to support this on tc-admin https://github.com/taskcluster/tc-admin/pull/71

**Comment by jschwartzentruber** [comment]
Fixed in tc-admin 2.5.0
