### ISSUE TITLE
how to use....?

### ISSUE THREAD

**Issue by am06** [MozillaSecurity/fuzzing-tc#9]
Hi all,

how do I use this to fuzz firefox in a container in AWS? 

Thanks,

**Comment by La0** [comment]
Hello,

This is an internal project to manage our fuzzing resources, not to run fuzzing itself.

You might be interested in those links:

- https://firefox-source-docs.mozilla.org/tools/fuzzing/index.html
- https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Fuzzing_Interface
- https://blog.mozilla.org/security/2019/07/10/grizzly/
- https://github.com/MozillaSecurity/FuzzManager/
